name: Backend CI/CD

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r backend/requirements.txt
      - name: Start server
        run: python backend/server.py --build-test
